// Character roster — 36 characters. Each is a stat spread + starting weapon +
// one signature trait (engine-implemented via trait.key in game.js).
// Base player stats before modifiers: 80 Max HP, everything else 0.

export const CHARACTERS = [
  { id: 'bulwark', name: 'Bulwark', sym: '⛨', roles: ['tank', 'melee'],
    stats: { maxHp: 80, armor: 8, speed: -20 }, weapon: 'gravemaul',
    trait: { key: 'kb_immune_big', hitbox: 1.4 },
    desc: 'Twice the health and immune to pulls and forced movement, but a far bigger target (hitbox ×1.4).' },
  { id: 'voltaic', name: 'Voltaic', sym: '⚡', roles: ['elemental'],
    stats: { elementalDamage: 20, meleeDamage: -50 }, weapon: 'sparkbolt',
    trait: { key: 'chain_attacks', chance: 0.3, factor: 0.6, range: 170 },
    desc: 'Attacks have a 30% chance to chain lightning to a nearby enemy at 60% damage.' },
  { id: 'magnate', name: 'Magnate', sym: '⛃', roles: ['economy'],
    stats: { luck: 8 }, weapon: 'pebbleshot',
    trait: { key: 'shop_broker', discount: 25, slots: 5 },
    desc: 'Shop prices −25% and the first reroll each shop is free, but only 5 weapon slots.' },
  { id: 'wisp', name: 'Wisp', sym: '❍', roles: ['dodge'],
    stats: { dodge: 40, speed: 10 }, weapon: 'threadneedle',
    trait: { key: 'dodge_master', cap: 90, hpCap: 20, dmgPerDodge: 1 },
    desc: 'Dodge cap raised to 90% and +1% Damage per 1% Dodge, but Max HP is capped at 20.' },
  { id: 'cogsmith', name: 'Cogsmith', sym: '⚙', roles: ['engineering'],
    stats: { engineering: 10 }, weapon: null,
    trait: { key: 'no_weapons_turrets', turrets: 2, inheritDmg: 0.5 },
    desc: 'Cannot equip weapons; starts with 2 Bolt Turrets that inherit half of Damage%.' },
  { id: 'lamprey', name: 'Lamprey', sym: '༄', roles: ['lifesteal'],
    stats: { lifeSteal: 8 }, weapon: 'twinlash',
    trait: { key: 'no_regen_growth', hpPerRoom: 2 },
    desc: 'HP Regen does nothing; gains +2 permanent Max HP for every room cleared.' },
  { id: 'powderkeg', name: 'Powderkeg', sym: '✸', roles: ['economy', 'elemental'],
    stats: { maxHp: 10 }, weapon: 'kegbomb',
    trait: { key: 'mat_detonate', dmg: 8, radius: 90 },
    desc: 'Materials detonate for 8 area damage around you when picked up.' },
  { id: 'echo', name: 'Echo', sym: '〜', roles: ['melee'],
    stats: { attackSpeed: -15, damage: 5 }, weapon: 'rustcleaver',
    trait: { key: 'echo_4th', echoes: 2, factor: 0.5 },
    desc: 'Every 4th attack echoes twice more at 50% damage.' },
  { id: 'quartermaster', name: 'Quartermaster', sym: '⚒', roles: ['economy'],
    stats: { damage: 10 }, weapon: 'gravelmouth',
    trait: { key: 'weapons_only_shop', discountWeapons: 20 },
    desc: 'Can only ever buy weapons — never items — and weapons cost 20% less.' },
  { id: 'gilded_one', name: 'Gilded One', sym: '☼', roles: ['economy', 'luck'],
    stats: { luck: 15, harvesting: 4 }, weapon: 'vaultspike',
    trait: { key: 'legendary_shop', slots: 2 },
    desc: 'Shop slots are always legendary — but there are only 2 of them.' },
  { id: 'chameleon', name: 'Chameleon', sym: '◐', roles: ['luck'],
    stats: { luck: 5 }, weapon: 'fanblade',
    trait: { key: 'random_room_stat' },
    desc: 'Gains a different random temporary stat boost in every room.' },
  { id: 'tollkeeper', name: 'Tollkeeper', sym: '⚖', roles: ['economy'],
    stats: { harvesting: 5 }, weapon: 'pikefang',
    trait: { key: 'greed_curse', matMult: 2, enemyHp: 1.25 },
    desc: 'Enemies drop double materials but have +25% HP (affects the whole party).' },
  { id: 'stillness', name: 'Stillness', sym: '◈', roles: ['ranged'],
    stats: { damage: 10, speed: -10 }, weapon: 'longbarrel',
    trait: { key: 'still_charge', ratePerSec: 50, max: 100 },
    desc: 'Standing still charges the next attack, up to +100% damage.' },
  { id: 'redmaw', name: 'Redmaw', sym: '⽕', roles: ['melee'],
    stats: { meleeDamage: 20, maxHp: 15 }, weapon: 'emberfang',
    trait: { key: 'berserk_missing', perMissing: 1 },
    desc: 'Deals +1% Damage for every 1% of HP missing.' },
  { id: 'glasswing', name: 'Glasswing', sym: '⟡', roles: ['speed', 'dodge'],
    stats: { speed: 15, dodge: 10 }, weapon: 'hailburst',
    trait: { key: 'glass', dealMult: 1.5, takeMult: 1.5 },
    desc: 'Deals +50% damage — and takes +50% damage.' },
  { id: 'twinsoul', name: 'Twinsoul', sym: '⧉', roles: ['engineering'],
    stats: { engineering: 3 }, weapon: 'pebbleshot',
    trait: { key: 'mirror_drone', factor: 0.5 },
    desc: 'A mirror-drone hovers beside you, copying your first weapon at 50% damage.' },
  { id: 'bastion', name: 'Bastion', sym: '▣', roles: ['tank'],
    stats: { armor: 5, maxHp: 20 }, weapon: 'pikefang',
    trait: { key: 'armor_growth', perRoom: 1, dodgeCap: 30 },
    desc: 'Gains +1 permanent Armor each room cleared, but Dodge is capped at 30%.' },
  { id: 'fleetfoot', name: 'Fleetfoot', sym: '➶', roles: ['speed'],
    stats: { speed: 30, maxHp: -10 }, weapon: 'threadneedle',
    trait: { key: 'speed_to_damage', per: 2 },
    desc: 'Gains +1% Damage for every 2% Speed bonus.' },
  { id: 'duskblade', name: 'Duskblade', sym: '☽', roles: ['crit', 'melee'],
    stats: { critChance: 25, maxHp: -25 }, weapon: 'vaultspike',
    trait: { key: 'crit_x3' },
    desc: 'Critical hits deal ×3 damage instead of ×2.' },
  { id: 'highroller', name: 'Highroller', sym: '⚄', roles: ['luck', 'economy'],
    stats: { luck: 25 }, weapon: 'gravelmouth',
    trait: { key: 'no_compound_reroll' },
    desc: 'Reroll cost never compounds within a shop.' },
  { id: 'archivist', name: 'Archivist', sym: '✎', roles: ['economy'],
    stats: { luck: 5, harvesting: 3 }, weapon: 'bogflask',
    trait: { key: 'five_choices', choices: 5 },
    desc: 'Level-ups offer 5 choices instead of 4.' },
  { id: 'cindermage', name: 'Cindermage', sym: '♨', roles: ['elemental'],
    stats: { elementalDamage: 15, rangedDamage: -20 }, weapon: 'cinderspray',
    trait: { key: 'burn_attacks', dps: 4, dur: 2 },
    desc: 'All attacks ignite for 4 damage/s over 2 s (burn scales with Elemental Damage).' },
  { id: 'frostcaller', name: 'Frostcaller', sym: '❅', roles: ['elemental'],
    stats: { elementalDamage: 12, speed: 5 }, weapon: 'frostjar',
    trait: { key: 'slow_attacks', mult: 0.6, dur: 1.2 },
    desc: 'All attacks chill, slowing enemies by 40% for 1.2 seconds.' },
  { id: 'longshot', name: 'Longshot', sym: '⌖', roles: ['ranged'],
    stats: { rangedDamage: 15, range: 60 }, weapon: 'longbarrel',
    trait: { key: 'far_bonus', dist: 250, bonus: 25 },
    desc: 'Deals +25% damage to enemies further than 250 units away.' },
  { id: 'threader', name: 'Threader', sym: '☍', roles: ['ranged'],
    stats: { rangedDamage: 10 }, weapon: 'coilgun',
    trait: { key: 'pierce_innate', add: 1 },
    desc: 'All projectiles pierce +1 enemy.' },
  { id: 'skirmisher', name: 'Skirmisher', sym: '⇶', roles: ['ranged', 'speed'],
    stats: { rangedDamage: 8, speed: 12 }, weapon: 'fanblade',
    trait: { key: 'move_ranged_bonus', bonus: 20 },
    desc: 'Gains +20% Ranged Damage while moving.' },
  { id: 'tinker', name: 'Tinker', sym: '⚙', roles: ['engineering'],
    stats: { engineering: 6 }, weapon: 'bolt_turret',
    trait: { key: 'structures_fast', rate: 1.25, slotCap: 4 },
    desc: 'Structures attack 25% faster, but you have only 4 weapon slots.' },
  { id: 'hivewright', name: 'Hivewright', sym: '⬡', roles: ['engineering'],
    stats: { engineering: 4, maxHp: 10 }, weapon: 'guard_drone',
    trait: { key: 'free_drone_floor' },
    desc: 'Gains a free Guard Drone at the start of every floor.' },
  { id: 'ironclad', name: 'Ironclad', sym: '⛊', roles: ['tank', 'melee'],
    stats: { armor: 10, speed: -15 }, weapon: 'gravemaul',
    trait: { key: 'armor_to_damage', perArmor: 1 },
    desc: 'Gains +1% Damage per point of Armor.' },
  { id: 'zephyr', name: 'Zephyr', sym: '𖤓', roles: ['dodge', 'speed', 'crit'],
    stats: { dodge: 20, speed: 15, maxHp: -15 }, weapon: 'twinlash',
    trait: { key: 'dodge_burst', speed: 40, dur: 1.5 },
    desc: 'Dodging grants a burst of +40% Speed and the next attack is a guaranteed crit.' },
  { id: 'mirage', name: 'Mirage', sym: '≋', roles: ['dodge'],
    stats: { dodge: 25 }, weapon: 'frostscythe',
    trait: { key: 'dodge_retaliate', dmg: 10, radius: 110 },
    desc: 'Dodging releases a retaliatory nova dealing 10 damage around you.' },
  { id: 'bloodpetal', name: 'Bloodpetal', sym: '❀', roles: ['lifesteal'],
    stats: { lifeSteal: 6, damage: 5, maxHp: -10 }, weapon: 'serpent_awl',
    trait: { key: 'kill_heal', amount: 1 },
    desc: 'Every kill heals 1 HP.' },
  { id: 'hemomancer', name: 'Hemomancer', sym: '🩸', roles: ['lifesteal'],
    stats: { lifeSteal: 10, maxHp: -20 }, weapon: 'stormlance',
    trait: { key: 'overheal_shield', cap: 20 },
    desc: 'Life steal beyond full HP becomes a shield of up to 20.' },
  { id: 'jester', name: 'Jester', sym: '♦', roles: ['crit', 'luck'],
    stats: { critChance: 10, luck: 10 }, weapon: 'fanblade',
    trait: { key: 'crit_ramp', per: 5 },
    desc: 'Each non-crit attack adds +5% Crit Chance until the next crit lands.' },
  { id: 'lancer', name: 'Lancer', sym: '†', roles: ['crit', 'melee'],
    stats: { meleeDamage: 12, critChance: 8 }, weapon: 'pikefang',
    trait: { key: 'first_hit_crit_innate' },
    desc: 'The first hit in every room is a guaranteed critical.' },
  { id: 'courier', name: 'Courier', sym: '➳', roles: ['speed', 'economy'],
    stats: { speed: 10, harvesting: 2 }, weapon: 'pebbleshot',
    trait: { key: 'momentum', speedPerRoom: 2 },
    desc: 'Gains +2% permanent Speed each room cleared.' },
];

export const CHAR_BY_ID = Object.fromEntries(CHARACTERS.map(c => [c.id, c]));
