// Item catalog — the Great Rebalance edition (single file, ≥100 items).
// Schema: { id, name, rarity, price, stats?, hooks?, desc? }
//   stats: flat sheet bonuses on the ten stats
//   hooks: engine effects aggregated in game.js _recomputeItems
// Healing hooks (regen/lifesteal/killHeal/...) are SOURCES — Recovery
// amplifies all of them. Crit hooks are the only way to crit (default ×2).
// Status hooks (burn/chill/chain/statusBoost) scale with Attunement.

export const ITEMS = [
  // ============ stat packages — commons, single stat ============
  { id: 'hardtack_ration', name: 'Hardtack Ration', rarity: 'common', price: 11,
    stats: { vitality: 5 } },
  { id: 'grindstone_chip', name: 'Grindstone Chip', rarity: 'common', price: 12,
    stats: { ferocity: 4 } },
  { id: 'springwound_cog', name: 'Springwound Cog', rarity: 'common', price: 13,
    stats: { tempo: 4 } },
  { id: 'iron_rivet_plate', name: 'Iron Rivet Plate', rarity: 'common', price: 12,
    stats: { grit: 1 } },
  { id: 'softsole_boots', name: 'Softsole Boots', rarity: 'common', price: 12,
    stats: { reflex: 4 } },
  { id: 'cavemoss_salve', name: 'Cavemoss Salve', rarity: 'common', price: 10,
    stats: { recovery: 6 } },
  { id: 'tinkers_pliers', name: "Tinker's Pliers", rarity: 'common', price: 12,
    stats: { ingenuity: 1 } },
  { id: 'flintspark_shard', name: 'Flintspark Shard', rarity: 'common', price: 12,
    stats: { attunement: 4 } },
  { id: 'tin_lantern', name: 'Tin Lantern', rarity: 'common', price: 11,
    stats: { greed: 3 } },
  { id: 'vaultwatch_spyglass', name: 'Vaultwatch Spyglass', rarity: 'common', price: 11,
    stats: { reach: 12 } },

  // ============ stat packages — commons, duos ============
  { id: 'copper_band', name: 'Copper Band', rarity: 'common', price: 14,
    stats: { vitality: 4, recovery: 4 } },
  { id: 'miners_mitts', name: "Miner's Mitts", rarity: 'common', price: 14,
    stats: { ferocity: 3, greed: 2 } },
  { id: 'fletchers_kit', name: "Fletcher's Kit", rarity: 'common', price: 14,
    stats: { reach: 8, ferocity: 3 } },
  { id: 'embercoal_lump', name: 'Embercoal Lump', rarity: 'common', price: 15,
    stats: { attunement: 3, ferocity: 3 } },
  { id: 'rustbitten_charm', name: 'Rustbitten Charm', rarity: 'common', price: 13,
    stats: { greed: 2, reach: 6 } },
  { id: 'padded_jerkin', name: 'Padded Jerkin', rarity: 'common', price: 14,
    stats: { grit: 1, vitality: 3 } },
  { id: 'quickstep_laces', name: 'Quickstep Laces', rarity: 'common', price: 14,
    stats: { tempo: 3, reflex: 3 } },
  { id: 'servo_winder', name: 'Servo Winder', rarity: 'common', price: 14,
    stats: { ingenuity: 1, tempo: 3 } },
  { id: 'chillbottle', name: 'Chillbottle', rarity: 'common', price: 14,
    stats: { attunement: 3, recovery: 4 } },
  { id: 'loadbearer_straps', name: 'Loadbearer Straps', rarity: 'common', price: 14,
    stats: { grit: 1, greed: 2 } },

  // ============ stat packages — uncommons ============
  { id: 'oxblood_tonic', name: 'Oxblood Tonic', rarity: 'uncommon', price: 26,
    stats: { vitality: 20, tempo: -3 },
    desc: 'Costs you −3% Tempo.' },
  { id: 'flywheel_gauntlet', name: 'Flywheel Gauntlet', rarity: 'uncommon', price: 27,
    stats: { tempo: 9 } },
  { id: 'bulwark_pauldron', name: 'Bulwark Pauldron', rarity: 'uncommon', price: 27,
    stats: { grit: 4, vitality: 6, reflex: -4 },
    desc: 'Costs you −4% Reflex.' },
  { id: 'quicksilver_soles', name: 'Quicksilver Soles', rarity: 'uncommon', price: 28,
    stats: { tempo: 6, reflex: 5 } },
  { id: 'vault_servo_core', name: 'Vault Servo Core', rarity: 'uncommon', price: 27,
    stats: { ingenuity: 5, ferocity: -3 },
    desc: 'Costs you −3% Ferocity.' },
  { id: 'ashen_grimoire', name: 'Ashen Grimoire', rarity: 'uncommon', price: 26,
    stats: { attunement: 9, greed: 3 } },
  { id: 'ratcatchers_elixir', name: "Ratcatcher's Elixir", rarity: 'uncommon', price: 30,
    stats: { greed: 8, recovery: 5, ferocity: -3 },
    desc: 'Costs you −3% Ferocity.' },
  { id: 'surveyors_array', name: "Surveyor's Array", rarity: 'uncommon', price: 26,
    stats: { reach: 20, ferocity: 4 } },
  { id: 'whetstone_wheel', name: 'Whetstone Wheel', rarity: 'uncommon', price: 27,
    stats: { ferocity: 11, tempo: -3 },
    desc: 'Costs you −3% Tempo.' },
  { id: 'sistered_plates', name: 'Sistered Plates', rarity: 'uncommon', price: 27,
    stats: { grit: 2, reflex: 4 } },
  { id: 'assemblers_manual', name: "Assembler's Manual", rarity: 'uncommon', price: 28,
    stats: { ingenuity: 4, greed: 3, ferocity: -3 },
    desc: 'Costs you −3% Ferocity.' },

  // ============ stat packages — rares ============
  { id: 'heartstone_core', name: 'Heartstone Core', rarity: 'rare', price: 52,
    stats: { vitality: 40, recovery: 8, tempo: -8 },
    desc: 'Costs you −8% Tempo.' },
  { id: 'warcasters_sigil', name: "Warcaster's Sigil", rarity: 'rare', price: 55,
    stats: { ferocity: 22, attunement: 6, tempo: -8 },
    desc: 'Costs you −8% Tempo.' },
  { id: 'stormheart_metronome', name: 'Stormheart Metronome', rarity: 'rare', price: 54,
    stats: { tempo: 21, grit: -3 },
    desc: 'Costs you −3 Grit.' },
  { id: 'adamant_aegis', name: 'Adamant Aegis', rarity: 'rare', price: 52,
    stats: { grit: 8, vitality: 8, reflex: -9 },
    desc: 'Costs you −9% Reflex.' },
  { id: 'prism_lens_array', name: 'Prism Lens Array', rarity: 'rare', price: 54,
    stats: { attunement: 24, reach: 12, ferocity: -8 },
    desc: 'Costs you −8% Ferocity.' },
  { id: 'magnates_ledgerstone', name: "Magnate's Ledgerstone", rarity: 'rare', price: 56,
    stats: { greed: 17, vitality: 6, ferocity: -8 },
    desc: 'Costs you −8% Ferocity.' },
  { id: 'ghostweave_cloak', name: 'Ghostweave Cloak', rarity: 'rare', price: 54,
    stats: { reflex: 15, tempo: 4, vitality: -14 },
    desc: 'Costs you −14 Vitality.' },
  { id: 'foundry_heart', name: 'Foundry Heart', rarity: 'rare', price: 55,
    stats: { ingenuity: 9, vitality: 6, ferocity: -8 },
    desc: 'Costs you −8% Ferocity.' },

  // ============ healing sources (Recovery amplifies all of these) ============
  { id: 'cavemoss_poultice', name: 'Cavemoss Poultice', rarity: 'common', price: 13,
    hooks: { regen: { hps: 1 } }, desc: 'Recover 1 HP per second.' },
  { id: 'deepmoss_compress', name: 'Deepmoss Compress', rarity: 'uncommon', price: 28,
    hooks: { regen: { hps: 2 } }, desc: 'Recover 2 HP per second.' },
  { id: 'leech_locket', name: 'Leech Locket', rarity: 'common', price: 13,
    hooks: { lifesteal: { pct: 2 } }, desc: 'Heal 2% of damage dealt.' },
  { id: 'bloodgroove_blade', name: 'Bloodgroove Blade', rarity: 'uncommon', price: 28,
    stats: { ferocity: 7, tempo: -3 },
    hooks: { lifesteal: { pct: 4 } }, desc: 'Heal 4% of damage dealt. Costs you −3% Tempo.' },
  { id: 'grave_snack', name: 'Grave Snack', rarity: 'common', price: 12,
    hooks: { killHeal: { amount: 1 } }, desc: 'Kills heal 1 HP.' },
  { id: 'butchers_bill', name: "Butcher's Bill", rarity: 'uncommon', price: 29,
    stats: { vitality: 6 },
    hooks: { killHeal: { amount: 2 } }, desc: 'Kills heal 2 HP.' },
  { id: 'bandolier_of_salves', name: 'Bandolier of Salves', rarity: 'uncommon', price: 27,
    stats: { recovery: 5, grit: -1 },
    hooks: { roomClearHeal: { amount: 10 } }, desc: 'Heal 10 HP at every fight clear. Costs you −1 Grit.' },
  { id: 'sugarrock_shard', name: 'Sugarrock Shard', rarity: 'uncommon', price: 26,
    hooks: { materialHeal: { chance: 0.15, amount: 1 } }, desc: '15% chance to heal 1 HP when picking up a material.' },
  { id: 'second_wind_whistle', name: 'Second Wind Whistle', rarity: 'legendary', price: 90,
    stats: { recovery: 15, grit: -3 },
    hooks: { secondWind: { healPercent: 0.5 } }, desc: 'Once per floor: refuse death and stand back up at 50% Vitality. Costs you −3 Grit.' },
  { id: 'aegis_coil', name: 'Aegis Coil', rarity: 'rare', price: 55,
    stats: { grit: 3, reflex: -9 },
    hooks: { blockShield: { cooldown: 6 } }, desc: 'Blocks one hit entirely, then recharges for 6s. Costs you −9% Reflex.' },

  // ============ conditional items (30) ============
  { id: 'brawlers_knuckle', name: "Brawler's Knuckle", rarity: 'uncommon', price: 28,
    stats: { ferocity: 3, tempo: -3 },
    hooks: { condStats: { cond: { kind: 'enemyNear', r: 60 }, stats: { ferocity: 25 } } },
    desc: '+25% Ferocity while an enemy is within 60u. Costs you −3% Tempo.' },
  { id: 'snipers_discipline', name: "Sniper's Discipline", rarity: 'uncommon', price: 28,
    hooks: { condStats: { cond: { kind: 'noEnemyNear', r: 150 }, stats: { ferocity: 20 } } },
    desc: '+20% Ferocity while no enemy is within 150u.' },
  { id: 'clean_bill', name: 'Clean Bill of Health', rarity: 'uncommon', price: 27,
    stats: { ferocity: 3, tempo: -3 },
    hooks: { condStats: { cond: { kind: 'hpAbove', pct: 90 }, stats: { ferocity: 20 } } },
    desc: '+20% Ferocity while above 90% HP. Costs you −3% Tempo.' },
  { id: 'cornered_rat', name: 'Cornered Rat', rarity: 'common', price: 14,
    hooks: { condStats: { cond: { kind: 'hpBelow', pct: 35 }, stats: { ferocity: 15 } } },
    desc: '+15% Ferocity while below 35% HP.' },
  { id: 'adrenal_gland', name: 'Adrenal Gland', rarity: 'uncommon', price: 28,
    hooks: { condStats: { cond: { kind: 'afterKill', dur: 3 }, stats: { tempo: 12 } } },
    desc: '+12% Tempo for 3s after a kill.' },
  { id: 'first_blood_pennant', name: 'First Blood Pennant', rarity: 'uncommon', price: 27,
    stats: { ferocity: 3, tempo: -3 },
    hooks: { condStats: { cond: { kind: 'firstKill', dur: 3 }, stats: { tempo: 15 } } },
    desc: "+15% Tempo for 3s after a fight's first kill.",
    desc: 'Costs you −3% Tempo.' },
  { id: 'wanderers_soles', name: "Wanderer's Soles", rarity: 'common', price: 13,
    hooks: { condStats: { cond: { kind: 'moving' }, stats: { tempo: 8 } } },
    desc: '+8% Tempo while moving.' },
  { id: 'planted_heels', name: 'Planted Heels', rarity: 'common', price: 13,
    hooks: { condStats: { cond: { kind: 'still' }, stats: { grit: 4 } } },
    desc: '+4 Grit while standing still.' },
  { id: 'doorbreaker_charm', name: 'Doorbreaker Charm', rarity: 'uncommon', price: 27,
    hooks: { condStats: { cond: { kind: 'roomEntry', dur: 10 }, stats: { ferocity: 15 } } },
    desc: '+15% Ferocity for the first 10s of every fight.' },
  { id: 'regicide_edge', name: 'Regicide Edge', rarity: 'rare', price: 54,
    stats: { ferocity: 8, tempo: -8 },
    hooks: { condStats: { cond: { kind: 'bossRoom' }, stats: { ferocity: 25 } } },
    desc: '+25% Ferocity during the Siege. Costs you −8% Tempo.' },
  { id: 'phalanx_badge', name: 'Phalanx Badge', rarity: 'uncommon', price: 26,
    stats: { ferocity: 3, tempo: -3 },
    hooks: { condStats: { cond: { kind: 'allyNear', r: 150 }, stats: { grit: 4 } } },
    desc: '+4 Grit while an ally is within 150u. Costs you −3% Tempo.' },
  { id: 'dragons_bed', name: "Dragon's Bed", rarity: 'uncommon', price: 29,
    hooks: { condStats: { cond: { kind: 'onMaterials', r: 30, cap: 10 }, stats: { grit: 2 } } },
    desc: '+2 Grit for each material you stand on (up to 10).' },
  { id: 'skirmish_garb', name: 'Skirmish Garb', rarity: 'common', price: 14,
    hooks: { condStats: { cond: { kind: 'moving' }, stats: { reflex: 6 } } },
    desc: '+6% Reflex while moving.' },
  { id: 'duelists_veil', name: "Duelist's Veil", rarity: 'uncommon', price: 28,
    stats: { ferocity: 3, tempo: -3 },
    hooks: { condStats: { cond: { kind: 'enemyNear', r: 60 }, stats: { reflex: 10 } } },
    desc: '+10% Reflex while an enemy is within 60u. Costs you −3% Tempo.' },
  { id: 'hermit_wrap', name: 'Hermit Wrap', rarity: 'common', price: 13,
    hooks: { condStats: { cond: { kind: 'noEnemyNear', r: 150 }, stats: { recovery: 15 } } },
    desc: '+15% Recovery while no enemy is within 150u.' },
  { id: 'triage_tabard', name: 'Triage Tabard', rarity: 'uncommon', price: 27,
    hooks: { condStats: { cond: { kind: 'hpBelow', pct: 50 }, stats: { recovery: 25 } } },
    desc: '+25% Recovery while below half HP.' },
  { id: 'fresh_legs', name: 'Fresh Legs', rarity: 'common', price: 13,
    hooks: { condStats: { cond: { kind: 'roomEntry', dur: 8 }, stats: { tempo: 10 } } },
    desc: '+10% Tempo for the first 8s of every fight.' },
  { id: 'bloodscent_locket', name: 'Bloodscent Locket', rarity: 'uncommon', price: 28,
    stats: { ferocity: 3, tempo: -3 },
    hooks: { condStats: { cond: { kind: 'afterKill', dur: 3 }, stats: { ferocity: 12 } } },
    desc: '+12% Ferocity for 3s after a kill. Costs you −3% Tempo.' },
  { id: 'executioners_hood', name: "Executioner's Hood", rarity: 'rare', price: 52,
    stats: { ferocity: 8, tempo: -8 },
    hooks: { condStats: { cond: { kind: 'bossRoom' }, stats: { attunement: 20 } } },
    desc: '+20% Attunement during the Siege. Costs you −8% Tempo.' },
  { id: 'emberstoked_bellows', name: 'Emberstoked Bellows', rarity: 'uncommon', price: 27,
    hooks: { condStats: { cond: { kind: 'enemyNear', r: 90 }, stats: { attunement: 12 } } },
    desc: '+12% Attunement while an enemy is within 90u.' },
  { id: 'longwatch_lens', name: 'Longwatch Lens', rarity: 'common', price: 14,
    hooks: { condStats: { cond: { kind: 'still' }, stats: { reach: 20 } } },
    desc: '+20 Reach while standing still.' },
  { id: 'caravan_flag', name: 'Caravan Flag', rarity: 'uncommon', price: 26,
    stats: { ferocity: 3, tempo: -3 },
    hooks: { condStats: { cond: { kind: 'allyNear', r: 150 }, stats: { tempo: 8 } } },
    desc: '+8% Tempo while an ally is within 150u. Costs you −3% Tempo.' },
  { id: 'payload_harness', name: 'Payload Harness', rarity: 'common', price: 14,
    hooks: { condStats: { cond: { kind: 'onMaterials', r: 30, cap: 5 }, stats: { ferocity: 2 } } },
    desc: '+2% Ferocity for each material you stand on (up to 5).' },
  { id: 'vault_compass', name: 'Vault Compass', rarity: 'uncommon', price: 27,
    hooks: { condStats: { cond: { kind: 'roomEntry', dur: 10 }, stats: { greed: 5 } } },
    desc: '+5 Greed for the first 10s of every fight.' },
  { id: 'deadline_chronometer', name: 'Deadline Chronometer', rarity: 'rare', price: 53,
    stats: { ferocity: 8, tempo: -8 },
    hooks: { condStats: { cond: { kind: 'firstKill', dur: 4 }, stats: { ferocity: 20 } } },
    desc: "+20% Ferocity for 4s after a fight's first kill.",
    desc: 'Costs you −8% Tempo.' },
  { id: 'nervous_fingers', name: 'Nervous Fingers', rarity: 'common', price: 13,
    hooks: { condStats: { cond: { kind: 'hpBelow', pct: 50 }, stats: { tempo: 8 } } },
    desc: '+8% Tempo while below half HP.' },
  { id: 'ironblood_draught', name: 'Ironblood Draught', rarity: 'uncommon', price: 27,
    stats: { ferocity: 3, tempo: -3 },
    hooks: { condStats: { cond: { kind: 'hpAbove', pct: 75 }, stats: { grit: 3 } } },
    desc: '+3 Grit while above 75% HP. Costs you −3% Tempo.' },
  { id: 'warcamp_standard', name: 'Warcamp Standard', rarity: 'rare', price: 54,
    stats: { ferocity: 8, tempo: -8 },
    hooks: { condStats: { cond: { kind: 'allyNear', r: 180 }, stats: { ferocity: 10 } } },
    desc: '+10% Ferocity while an ally is within 180u. Costs you −8% Tempo.' },
  { id: 'scavengers_instinct', name: "Scavenger's Instinct", rarity: 'common', price: 14,
    hooks: { condStats: { cond: { kind: 'onMaterials', r: 30, cap: 8 }, stats: { greed: 1 } } },
    desc: '+1 Greed for each material you stand on (up to 8).' },
  { id: 'boneset_splint', name: 'Boneset Splint', rarity: 'uncommon', price: 28,
    hooks: { condStats: { cond: { kind: 'hpBelow', pct: 60 }, stats: { grit: 3, recovery: 10 } } },
    desc: '+3 Grit and +10% Recovery while below 60% HP.' },
  { id: 'overcharged_core', name: 'Overcharged Core', rarity: 'rare', price: 56,
    stats: { ferocity: 8, tempo: -8 },
    hooks: { condStats: { cond: { kind: 'hpAbove', pct: 90 }, stats: { tempo: 15, ferocity: 10 } } },
    desc: '+15% Tempo and +10% Ferocity while above 90% HP. Costs you −8% Tempo.' },

  // ============ crit granters (crit is not a stat) ============
  { id: 'headsmans_memento', name: "Headsman's Memento", rarity: 'uncommon', price: 29,
    stats: { ferocity: 3, tempo: -3 },
    hooks: { critAfterKill: true }, desc: 'Your first attack after a kill crits. Costs you −3% Tempo.' },
  { id: 'tenth_strike_tally', name: 'Tenth-Strike Tally', rarity: 'uncommon', price: 28,
    hooks: { critEveryN: { n: 10 } }, desc: 'Every 10th attack crits.' },
  { id: 'rimeheart_prism', name: 'Rimeheart Prism', rarity: 'rare', price: 55,
    stats: { ferocity: 8, tempo: -8 },
    hooks: { critVsChilled: true }, desc: 'Attacks against chilled enemies crit. Costs you −8% Tempo.' },
  { id: 'pyre_sight', name: 'Pyre Sight', rarity: 'rare', price: 55,
    stats: { ferocity: 8, tempo: -8 },
    hooks: { critVsBurning: true }, desc: 'Attacks against burning enemies crit. Costs you −8% Tempo.' },
  { id: 'assassins_primer', name: "Assassin's Primer", rarity: 'rare', price: 54,
    stats: { ferocity: 8, tempo: -8 },
    hooks: { critVsFullHp: true }, desc: 'Attacks against full-HP enemies crit. Costs you −8% Tempo.' },
  { id: 'openers_oath', name: "Opener's Oath", rarity: 'uncommon', price: 26,
    stats: { ferocity: 3, tempo: -3 },
    hooks: { firstHitCrit: true }, desc: 'Your first attack in every fight crits. Costs you −3% Tempo.' },
  { id: 'jesters_own_deck', name: "Jester's Own Deck", rarity: 'legendary', price: 88,
    stats: { ferocity: 8, tempo: -8 },
    hooks: { critEveryN: { n: 6 } }, desc: 'Every 6th attack crits. Costs you −8% Tempo.' },
  { id: 'crit_salve', name: 'Red Ribbon Salve', rarity: 'uncommon', price: 27,
    hooks: { critHeal: { amount: 2 } }, desc: 'Critical hits heal 2 HP.' },
  { id: 'matadors_cape', name: "Matador's Cape", rarity: 'uncommon', price: 28,
    stats: { tempo: 2, grit: -1 },
    hooks: { nextAttackAfterDodge: { bonus: 50 } }, desc: 'After a dodge, your next attack deals +50% damage. Costs you −1 Grit.' },

  // ============ per-pickup procs ============
  { id: 'sparkdust_pouch', name: 'Sparkdust Pouch', rarity: 'uncommon', price: 28,
    hooks: { pickupBlast: { damage: 6, radius: 70 } },
    desc: 'Picking up a material detonates it for 6 attuned damage (radius 70).' },
  { id: 'detonation_tithe', name: 'Detonation Tithe', rarity: 'rare', price: 54,
    stats: { greed: 7, ferocity: -8 },
    hooks: { pickupBlast: { damage: 12, radius: 90 } },
    desc: 'Picking up a material detonates it for 12 attuned damage (radius 90). Costs you −8% Ferocity.' },
  { id: 'greedwind_charm', name: 'Greedwind Charm', rarity: 'uncommon', price: 27,
    stats: { greed: 2, ferocity: -3 },
    hooks: { pickupTempo: { tempo: 10, duration: 2, maxStacks: 3 } },
    desc: 'Picking up a material grants +10% Tempo for 2s (stacks 3×). Costs you −3% Ferocity.' },
  { id: 'loose_change', name: 'Loose Change', rarity: 'common', price: 13,
    hooks: { pickupBonusChance: { chance: 0.05 } },
    desc: '5% chance a picked-up material is worth one extra.' },
  { id: 'magpies_eye', name: "Magpie's Eye", rarity: 'uncommon', price: 28,
    hooks: { pickupBonusChance: { chance: 0.08 } },
    desc: '8% chance a picked-up material is worth one extra.' },

  // ============ status spreaders (Attunement-scaled) ============
  { id: 'pitchfire_vial', name: 'Pitchfire Vial', rarity: 'common', price: 14,
    hooks: { burnOnHit: { chance: 0.15, dps: 3, duration: 2 } },
    desc: '15% chance on hit to ignite: 3 dmg/s for 2s.' },
  { id: 'wick_and_tallow', name: 'Wick and Tallow', rarity: 'uncommon', price: 28,
    stats: { attunement: 4, ferocity: -3 },
    hooks: { burnOnHit: { chance: 0.25, dps: 4, duration: 2 } },
    desc: '25% chance on hit to ignite: 4 dmg/s for 2s. Costs you −3% Ferocity.' },
  { id: 'frostbite_ring', name: 'Frostbite Ring', rarity: 'common', price: 14,
    hooks: { chillOnHit: { chance: 0.15, mult: 0.6, duration: 1.2 } },
    desc: '15% chance on hit to chill: −40% speed for 1.2s.' },
  { id: 'glacier_salt', name: 'Glacier Salt', rarity: 'uncommon', price: 28,
    hooks: { chillOnHit: { chance: 0.25, mult: 0.55, duration: 1.5 } },
    desc: '25% chance on hit to chill: −45% speed for 1.5s.' },
  { id: 'galvanic_coil', name: 'Galvanic Coil', rarity: 'uncommon', price: 29,
    stats: { attunement: 4, ferocity: -3 },
    hooks: { chainOnHit: { chance: 0.2, damage: 8, range: 160 } },
    desc: '20% chance on hit to arc 8 attuned damage to a nearby enemy. Costs you −3% Ferocity.' },
  { id: 'kindlers_manual', name: "Kindler's Manual", rarity: 'uncommon', price: 28,
    stats: { attunement: 4 },
    hooks: { statusBoost: { pct: 15 } },
    desc: 'Your burns, chills, chains and blasts are 15% stronger.' },
  { id: 'stormbinder_loop', name: 'Stormbinder Loop', rarity: 'rare', price: 56,
    stats: { attunement: 10, ferocity: -8 },
    hooks: { chainOnHit: { chance: 0.3, damage: 14, range: 180 }, statusBoost: { pct: 10 } },
    desc: '30% chance on hit to arc 14 attuned damage; statuses 10% stronger. Costs you −8% Ferocity.' },

  // ============ aura / party items ============
  { id: 'rallying_horn', name: 'Rallying Horn', rarity: 'uncommon', price: 28,
    stats: { vitality: 8, tempo: -3 },
    hooks: { allyAura: { radius: 150, stats: { ferocity: 8 } } },
    desc: 'Allies within 150u gain +8% Ferocity. Costs you −3% Tempo.' },
  { id: 'chirurgeons_censer', name: "Chirurgeon's Censer", rarity: 'uncommon', price: 28,
    hooks: { allyAura: { radius: 150, stats: { recovery: 15 } } },
    desc: 'Allies within 150u gain +15% Recovery.' },
  { id: 'drillmasters_whistle', name: "Drillmaster's Whistle", rarity: 'uncommon', price: 28,
    stats: { vitality: 8, tempo: -3 },
    hooks: { allyAura: { radius: 150, stats: { tempo: 6 } } },
    desc: 'Allies within 150u gain +6% Tempo. Costs you −3% Tempo.' },
  { id: 'standard_of_the_vault', name: 'Standard of the Vault', rarity: 'rare', price: 56,
    stats: { vitality: 20, tempo: -8 },
    hooks: { allyAura: { radius: 170, stats: { ferocity: 6, grit: 2 } } },
    desc: 'Allies within 170u gain +6% Ferocity and +2 Grit. Costs you −8% Tempo.' },
  { id: 'lodemothers_chime', name: "Lodemother's Chime", rarity: 'rare', price: 55,
    stats: { tempo: 7, grit: -3 },
    hooks: { reviveSpeed: { mult: 0.5 }, allyAura: { radius: 140, stats: { recovery: 10 } } },
    desc: 'You revive allies 50% faster; allies within 140u gain +10% Recovery. Costs you −3 Grit.' },

  // ============ combat misc ============
  { id: 'thorncoat', name: 'Thorncoat', rarity: 'uncommon', price: 27,
    stats: { grit: 1 },
    hooks: { thorns: { damage: 4 } },
    desc: 'Attackers take 4 damage when they hit you.' },
  { id: 'cinder_cloak', name: 'Cinder Cloak', rarity: 'uncommon', price: 29,
    stats: { grit: 1, reflex: -4 },
    hooks: { contactAura: { dps: 4, radius: 80 } },
    desc: 'Enemies within 80u smolder for 4 damage per second. Costs you −4% Reflex.' },
  { id: 'bulette_plating', name: 'Bulette Plating', rarity: 'rare', price: 55,
    stats: { grit: 3, reflex: -9 },
    hooks: { onHurtRetaliate: { damage: 12, radius: 110 } },
    desc: 'Taking a hit releases an attuned nova: 12 damage within 110u. Costs you −9% Reflex.' },
  { id: 'slaughter_rhythm', name: 'Slaughter Rhythm', rarity: 'uncommon', price: 29,
    hooks: { killTempo: { tempo: 8, duration: 3, maxStacks: 4 } },
    desc: 'Kills grant +8% Tempo for 3s (stacks 4×).' },
  { id: 'gravediggers_pact', name: "Gravedigger's Pact", rarity: 'rare', price: 56,
    stats: { vitality: 20, tempo: -8 },
    hooks: { vitalityOnKill: { amount: 1, cap: 30 } },
    desc: 'Kills grant +1 permanent Vitality (up to +30 per run). Costs you −8% Tempo.' },
  { id: 'powder_charges', name: 'Powder Charges', rarity: 'uncommon', price: 29,
    stats: { ferocity: 3, tempo: -3 },
    hooks: { killExplode: { chance: 0.2, damage: 10, radius: 80 } },
    desc: '20% chance for kills to detonate: 10 attuned damage within 80u. Costs you −3% Tempo.' },
  { id: 'giantsbane_bolt', name: 'Giantsbane Bolt', rarity: 'rare', price: 55,
    stats: { ferocity: 8, tempo: -8 },
    hooks: { eliteBossDamage: { bonus: 25 } },
    desc: '+25% damage to elites and bosses. Costs you −8% Tempo.' },
  { id: 'drillbit_rounds', name: 'Drillbit Rounds', rarity: 'uncommon', price: 28,
    hooks: { extraPierce: { add: 1 } },
    desc: 'Your projectiles pierce +1 enemy.' },
  { id: 'splitting_chamber', name: 'Splitting Chamber', rarity: 'legendary', price: 95,
    stats: { ferocity: 8, tempo: -8 },
    hooks: { extraProjectiles: { add: 1 } },
    desc: 'Your ranged weapons fire +1 projectile. Costs you −8% Tempo.' },
  { id: 'rambounce_pads', name: 'Rambounce Pads', rarity: 'uncommon', price: 26,
    stats: { ferocity: 3, tempo: -3 },
    hooks: { knockbackBoost: { mult: 0.5 } },
    desc: 'Your knockback is 50% stronger. Costs you −3% Tempo.' },

  // ============ economy & growth ============
  { id: 'coin_of_return', name: 'Coin of Return', rarity: 'uncommon', price: 28,
    hooks: { interest: { rate: 5, cap: 10 } },
    desc: 'Earn 5% interest on held materials at each fight clear (max 10).' },
  { id: 'hagglers_tongue', name: "Haggler's Tongue", rarity: 'uncommon', price: 27,
    stats: { greed: 2, ferocity: -3 },
    hooks: { shopDiscount: { percent: 10 } },
    desc: 'Shop prices −10%. Costs you −3% Ferocity.' },
  { id: 'reroll_chit', name: 'Reroll Chit', rarity: 'common', price: 13,
    hooks: { freeRerolls: { count: 1 } },
    desc: 'The first reroll in every shop is free.' },
  { id: 'quick_study', name: 'Quick Study', rarity: 'common', price: 13,
    hooks: { xpBonus: { percent: 10 } },
    desc: '+10% XP from materials.' },
  { id: 'archivists_folio', name: "Archivist's Folio", rarity: 'uncommon', price: 29,
    stats: { greed: 3 },
    hooks: { extraChoice: { n: 1 } },
    desc: 'Level-ups offer 1 extra choice.' },
  { id: 'growth_chart', name: 'Growth Chart', rarity: 'uncommon', price: 28,
    stats: { vitality: 8, tempo: -3 },
    hooks: { levelStats: { stats: { vitality: 2 } } },
    desc: '+2 permanent Vitality on every level-up. Costs you −3% Tempo.' },
  { id: 'deepvault_compact', name: 'Deepvault Compact', rarity: 'rare', price: 55,
    stats: { vitality: 20, tempo: -8 },
    hooks: { floorStats: { stats: { greed: 3, vitality: 4 } } },
    desc: '+3 Greed and +4 Vitality at the start of every floor. Costs you −8% Tempo.' },
  { id: 'doublestrike_ledger', name: 'Doublestrike Ledger', rarity: 'rare', price: 56,
    stats: { greed: 7, ferocity: -8 },
    hooks: { doubleMaterials: { chance: 0.15 } },
    desc: '15% chance for kills to drop double materials. Costs you −8% Ferocity.' },
  { id: 'medics_satchel', name: "Medic's Satchel", rarity: 'uncommon', price: 27,
    hooks: { reviveSpeed: { mult: 0.5 } },
    desc: 'You revive allies 50% faster.' },

  // ============ summon boosters ============
  { id: 'foremans_manual', name: "Foreman's Manual", rarity: 'uncommon', price: 28,
    stats: { ingenuity: 2, ferocity: -3 },
    hooks: { summonBoost: { damage: 20, hp: 20 } },
    desc: 'Your summons deal +20% damage and have +20% HP. Costs you −3% Ferocity.' },
  { id: 'overclock_governor', name: 'Overclock Governor', rarity: 'rare', price: 55,
    stats: { ingenuity: 6, ferocity: -8 },
    hooks: { summonBoost: { damage: 35, hp: 10 } },
    desc: 'Your summons deal +35% damage and have +10% HP. Costs you −8% Ferocity.' },

  // ============ legendaries ============
  { id: 'vault_sovereigns_crown', name: "Vault Sovereign's Crown", rarity: 'legendary', price: 96,
    stats: { greed: 22, vitality: 10, ferocity: -8 },
    desc: 'Costs you −8% Ferocity.' },
  { id: 'worldbreaker_sledge', name: 'Worldbreaker Sledge', rarity: 'legendary', price: 95,
    stats: { ferocity: 33, tempo: -8 },
    desc: 'Costs you −8% Tempo.' },
  { id: 'chronomancers_gear', name: "Chronomancer's Gear", rarity: 'legendary', price: 96,
    stats: { tempo: 27, reflex: 8, grit: -3 },
    desc: 'Costs you −3 Grit.' },
  { id: 'saints_reliquary', name: "Saint's Reliquary", rarity: 'legendary', price: 92,
    stats: { recovery: 45, grit: -3 },
    hooks: { regen: { hps: 1 } },
    desc: 'Recover 1 HP per second. Costs you −3 Grit.' },
  { id: 'architects_omnitool', name: "Architect's Omnitool", rarity: 'legendary', price: 96,
    stats: { ingenuity: 12, ferocity: -8 },
    hooks: { summonBoost: { damage: 25, hp: 25 } },
    desc: 'Your summons deal +25% damage and have +25% HP. Costs you −8% Ferocity.' },
  { id: 'tempest_codex', name: 'Tempest Codex', rarity: 'legendary', price: 95,
    stats: { attunement: 35, ferocity: -8 },
    hooks: { statusBoost: { pct: 15 } },
    desc: 'Your burns, chills, chains and blasts are 15% stronger. Costs you −8% Ferocity.' },
  { id: 'panoply_of_the_deep', name: 'Panoply of the Deep', rarity: 'legendary', price: 94,
    stats: { grit: 11, vitality: 15, reflex: -9 },
    desc: 'Costs you −9% Reflex.' },
  { id: 'horizon_glass', name: 'Horizon Glass', rarity: 'legendary', price: 93,
    stats: { reach: 40, ferocity: 18, tempo: -8 },
    desc: 'Costs you −8% Tempo.' },
  { id: 'banner_of_the_last_stand', name: 'Banner of the Last Stand', rarity: 'legendary', price: 98,
    stats: { vitality: 20, tempo: -8 },
    hooks: { allyAura: { radius: 180, stats: { ferocity: 10, recovery: 15 } } },
    desc: 'Allies within 180u gain +10% Ferocity and +15% Recovery. Costs you −8% Tempo.' },

  // ============ cursed goods ============
  // Deliberately overstatted for their price (~30–40% above a clean item) and
  // paid for with a curse that lands on the NEXT round only, then expires.
  // `curse.scope`: 'enemy' curses hit the shared round (co-op: everyone's
  // problem); 'self' curses only ever touch the buyer. Curses of the same
  // key stack additively when several are bought. The curse text is spelled
  // out in `desc` because a curse the card doesn't name is just a bug.
  { id: 'gravebound_locket', name: 'Gravebound Locket', rarity: 'uncommon', price: 30,
    stats: { vitality: 16, recovery: 10 },
    curse: { key: 'enemyHp', value: 0.05, scope: 'enemy' },
    desc: 'CURSED — next round only: every enemy has +5% HP (the whole party\'s round).' },
  { id: 'whipcrack_spur', name: 'Whipcrack Spur', rarity: 'uncommon', price: 31,
    stats: { tempo: 11, ferocity: 6 },
    curse: { key: 'enemySpd', value: 0.10, scope: 'enemy' },
    desc: 'CURSED — next round only: every enemy moves 10% faster (the whole party\'s round).' },
  { id: 'leadfoot_ballast', name: 'Leadfoot Ballast', rarity: 'uncommon', price: 29,
    stats: { grit: 5, vitality: 12 },
    curse: { key: 'tempo', value: -5, scope: 'self' },
    desc: 'CURSED — next round only: you have −5% Tempo.' },
  { id: 'blindfold_of_certainty', name: 'Blindfold of Certainty', rarity: 'uncommon', price: 32,
    stats: { ferocity: 12, attunement: 8 },
    curse: { key: 'reflex', value: -10, scope: 'self' },
    desc: 'CURSED — next round only: you have −10% Reflex.' },
  { id: 'scab_stitched_charm', name: 'Scab-Stitched Charm', rarity: 'rare', price: 52,
    stats: { vitality: 24, grit: 4 },
    hooks: { killHeal: { amount: 2 } },
    curse: { key: 'healHalf', value: 1, scope: 'self' },
    desc: 'Kills heal 2 HP. CURSED — next round only: all healing you receive is halved.' },
  { id: 'siege_bell', name: 'Siege Bell', rarity: 'rare', price: 55,
    stats: { ferocity: 16, reach: 18 },
    curse: { key: 'barrage', value: 1, scope: 'enemy' },
    desc: 'CURSED — next round only: one extra artillery barrage falls on the party.' },
  { id: 'hollow_kings_signet', name: "Hollow King's Signet", rarity: 'rare', price: 54,
    stats: { greed: 9, ferocity: 10 },
    curse: { key: 'enemyHp', value: 0.05, scope: 'enemy' },
    desc: 'CURSED — next round only: every enemy has +5% HP (the whole party\'s round).' },
  { id: 'quicksilver_vial', name: 'Quicksilver Vial', rarity: 'rare', price: 53,
    stats: { tempo: 15, reflex: 10 },
    curse: { key: 'healHalf', value: 1, scope: 'self' },
    desc: 'CURSED — next round only: all healing you receive is halved.' },
  { id: 'apostates_reliquary', name: "Apostate's Reliquary", rarity: 'legendary', price: 92,
    stats: { attunement: 30, ferocity: 12 },
    hooks: { statusBoost: { pct: 12 } },
    curse: { key: 'enemySpd', value: 0.10, scope: 'enemy' },
    desc: 'Your burns, chills, chains and blasts are 12% stronger. CURSED — next round only: every enemy moves 10% faster (the whole party\'s round).' },
  { id: 'the_bad_bargain', name: 'The Bad Bargain', rarity: 'legendary', price: 95,
    stats: { ferocity: 22, tempo: 12, vitality: 18 },
    curse: { key: 'barrage', value: 1, scope: 'enemy' },
    desc: 'CURSED — next round only: one extra artillery barrage falls on the party, and you take −5% Tempo with it.',
    curse2: { key: 'tempo', value: -5, scope: 'self' } },

  // ================================================================
  // PHASE 4 — §9.2's item tiers as content.
  //
  // Four things distinguish everything below from the catalog above.
  //
  // `penalty` is a MAGNITUDE, not a stat. §9.2's stat items grant a flat bonus
  // and roll the penalty randomly against another stat at the moment of the
  // grant, so the pairing is never memorised and every offer stays a real
  // question. The roll is per instance and lives on the player, not here.
  //
  // `lateWeight` is 0..1 and is the whole of late-game weighting. The shop
  // holds no region table; it passes one normalised progress scalar and the
  // item's own data decides. Adding region 5 changes no shop code.
  //
  // `perLevel` is what buying a second copy deepens (§9.3). Hook payloads are
  // NOT scaled by a blanket multiplier, because "stronger" is not the same
  // direction for every field — an explicit block has no direction to get wrong.
  //
  // And nothing here touches a cooldown. §9.2 bans it on every item for the
  // same reason §4.2 keeps it off ranks: it is the one thing that lets a narrow
  // build buy back its uptime, and the depth-versus-breadth pressure goes with
  // it. `validate_items` fails on the word; `econ_gate` fails on the effect.

  // ---------------- stat items, rolled penalty (§9.2 common tier) ----------
  { id: 'crooked_ledger', name: 'Crooked Ledger', rarity: 'common', price: 15,
    stats: { greed: 5 }, penalty: 3,
    desc: '+5 Greed, and −3 to one other stat, rolled when you take it.' },
  { id: 'butchers_apron', name: "Butcher's Apron", rarity: 'common', price: 16,
    stats: { ferocity: 7 }, penalty: 4,
    desc: '+7% Ferocity, and −4 to one other stat, rolled when you take it.' },
  { id: 'ballast_vest', name: 'Ballast Vest', rarity: 'common', price: 16,
    stats: { vitality: 12 }, penalty: 4,
    desc: '+12 Vitality, and −4 to one other stat, rolled when you take it.' },
  { id: 'gamblers_cuff', name: "Gambler's Cuff", rarity: 'uncommon', price: 26,
    stats: { reflex: 9 }, penalty: 5,
    desc: '+9% Reflex — dodge and crit both — and −5 to one other stat, rolled when you take it.' },
  { id: 'thaumic_shunt', name: 'Thaumic Shunt', rarity: 'uncommon', price: 28,
    stats: { attunement: 12 }, penalty: 6,
    desc: '+12% Attunement, and −6 to one other stat, rolled when you take it.' },
  { id: 'boneglass_lens', name: 'Boneglass Lens', rarity: 'uncommon', price: 27,
    stats: { ingenuity: 6 }, penalty: 4,
    desc: '+6 Ingenuity, and −4 to one other stat, rolled when you take it.' },
  { id: 'wardens_yoke', name: "Warden's Yoke", rarity: 'rare', price: 48,
    stats: { grit: 7, vitality: 14 }, penalty: 7,
    desc: '+7 Grit and +14 Vitality, and −7 to one other stat, rolled when you take it.' },
  { id: 'duelists_promise', name: "Duelist's Promise", rarity: 'rare', price: 52,
    stats: { ferocity: 16, reflex: 8 }, penalty: 8,
    desc: '+16% Ferocity and +8% Reflex, and −8 to one other stat, rolled when you take it.' },
  { id: 'the_long_odds', name: 'The Long Odds', rarity: 'legendary', price: 96,
    stats: { reflex: 22 }, penalty: 12,
    desc: '+22% Reflex, and −12 to one other stat, rolled when you take it.' },

  // ---------------- magnitude (§9.2) --------------------------------------
  // Splash radius, projectile count, PIERCE, chain jumps, duration. §5.9 puts
  // pierce here deliberately: it is the answer to an escorted target, and a
  // party that wants to punch through buys it rather than being handed it.
  { id: 'awl_of_the_line', name: 'Awl of the Line', rarity: 'rare', price: 46, lateWeight: 0.6,
    hooks: { extraPierce: { add: 1 } }, perLevel: { hooks: { extraPierce: { add: 1 } } },
    desc: 'Your bolts pierce 1 extra target. Each upgrade adds 1 more.' },
  { id: 'skewer_of_ruin', name: 'Skewer of Ruin', rarity: 'legendary', price: 104, lateWeight: 0.9,
    hooks: { extraPierce: { add: 3 } }, perLevel: { hooks: { extraPierce: { add: 2 } } },
    desc: 'Your bolts pierce 3 extra targets. Each upgrade adds 2 more.' },
  { id: 'split_quarrel', name: 'Split Quarrel', rarity: 'legendary', price: 112, lateWeight: 1,
    hooks: { extraProjectiles: { add: 1 } }, perLevel: { hooks: { extraProjectiles: { add: 1 } } },
    desc: 'Bolt skills fire at 1 extra target. Each upgrade adds 1 more.' },
  { id: 'giants_follow_through', name: "Giant's Follow-Through", rarity: 'uncommon', price: 30, lateWeight: 0.3,
    hooks: { knockbackBoost: { mult: 0.6 } },
    desc: 'Knockback riders push 60% further.' },
  { id: 'headhunters_tally', name: "Headhunter's Tally", rarity: 'rare', price: 58, lateWeight: 0.7,
    hooks: { eliteBossDamage: { bonus: 22 } }, perLevel: { hooks: { eliteBossDamage: { bonus: 12 } } },
    desc: '+22% damage to elites and bosses. Each upgrade adds 12%.' },
  { id: 'hairline_edge', name: 'Hairline Edge', rarity: 'rare', price: 54, lateWeight: 0.5,
    hooks: { critChance: { percent: 8 } }, perLevel: { hooks: { critChance: { percent: 5 } } },
    desc: '+8% crit chance on top of Reflex. Each upgrade adds 5%.' },
  { id: 'the_deep_cut', name: 'The Deep Cut', rarity: 'legendary', price: 118, lateWeight: 0.9,
    hooks: { critMult: { add: 0.9 } }, perLevel: { hooks: { critMult: { add: 0.4 } } },
    desc: 'Crits deal ×0.9 more. Each upgrade adds ×0.4.' },
  { id: 'ossuary_harness', name: 'Ossuary Harness', rarity: 'rare', price: 50, lateWeight: 0.4,
    hooks: { summonBoost: { damage: 25, hp: 25 } }, perLevel: { hooks: { summonBoost: { damage: 15, hp: 15 } } },
    desc: 'Your summons deal +25% damage and have +25% HP. Each upgrade adds 15%.' },

  // ---------------- rider (§9.2) ------------------------------------------
  // "Adds an effect the skill did not have." Every one of these lands through
  // the single composed-impact path, so it reaches skills nobody has authored.
  { id: 'emberwick_thread', name: 'Emberwick Thread', rarity: 'uncommon', price: 32, lateWeight: 0.5,
    hooks: { burnOnHit: { chance: 0.2, dps: 7, duration: 3 } },
    desc: '20% of hits set the target burning for 7 damage a second over 3s.' },
  { id: 'hoarfrost_shim', name: 'Hoarfrost Shim', rarity: 'uncommon', price: 33, lateWeight: 0.5,
    hooks: { chillOnHit: { chance: 0.22, mult: 0.65, duration: 2 } },
    desc: '22% of hits chill the target to 65% speed for 2s.' },
  { id: 'arcline_coil', name: 'Arcline Coil', rarity: 'rare', price: 56, lateWeight: 0.7,
    hooks: { chainOnHit: { chance: 0.25, damage: 14, range: 190 } },
    desc: '25% of hits arc to a second enemy within 190 units for 14 damage.' },
  { id: 'pyre_conductor', name: 'Pyre Conductor', rarity: 'legendary', price: 108, lateWeight: 0.9,
    hooks: { burnOnHit: { chance: 0.45, dps: 16, duration: 4 } },
    desc: '45% of hits set the target burning for 16 damage a second over 4s.' },

  // ---------------- domain add (§9.2's "domain swap", as an ADD) -----------
  // The tier is named swap; the section's governing rule is "an item may add,
  // never take away". These resolve the triangle as the BEST of the skill's own
  // domain and the granted one — a build gains the matchup it lacked and keeps
  // every matchup it had. See §9.2 for the reconciliation and the assumption.
  { id: 'iron_reading', name: 'Iron Reading', rarity: 'rare', price: 62, lateWeight: 0.8,
    hooks: { domainAdd: { domain: 'physical' } },
    desc: 'Your skills also resolve as Physical when that reads better (×1.25 into Spiritual).' },
  { id: 'the_quiet_argument', name: 'The Quiet Argument', rarity: 'rare', price: 62, lateWeight: 0.8,
    hooks: { domainAdd: { domain: 'mental' } },
    desc: 'Your skills also resolve as Mental when that reads better (×1.25 into Physical).' },
  { id: 'ghostlight_sigil', name: 'Ghostlight Sigil', rarity: 'legendary', price: 96, lateWeight: 1,
    hooks: { domainAdd: { domain: 'spiritual' } },
    desc: 'Your skills also resolve as Spiritual when that reads better (×1.25 into Mental).' },

  // ---------------- selector add (§9.2) -----------------------------------
  // Selector-ADD, never selector-swap. A crowd-clearing build that finds one
  // gains an elite-killer without losing its crowd clear and without spending a
  // point. The added selector re-ranks only what the skill's own range already
  // returns (§5.3 rule 1) — an item may not widen a search.
  { id: 'second_sight', name: 'Second Sight', rarity: 'rare', price: 66, lateWeight: 0.9,
    hooks: { selectorAdd: { select: 'highest_hp' } },
    desc: 'Bolt skills also strike the highest-HP target in range.' },
  { id: 'coup_de_grace', name: 'Coup de Grâce', rarity: 'rare', price: 64, lateWeight: 0.9,
    hooks: { selectorAdd: { select: 'lowest_hp' } },
    desc: 'Bolt skills also strike the lowest-HP target in range.' },
  { id: 'the_far_mark', name: 'The Far Mark', rarity: 'legendary', price: 98, lateWeight: 1,
    hooks: { selectorAdd: { select: 'objective_target' } },
    desc: 'Bolt skills also strike the objective — nest, mark, boss, elite — when one is in range.' },
];

export const ITEM_BY_ID = Object.fromEntries(ITEMS.map(it => [it.id, it]));

// Sprite ids — one icon per item, 24x24. Stamped rather than typed 146 times
// so the catalog and its art inventory cannot drift apart. Cosmetic only.
for (const it of ITEMS) it.spriteId = `item.${it.id}`;
