// Undervault item pack C — strange devices, charms, curios, living trinkets, contraptions (40 mechanical items)
export const PART = [
  // ---------- COMMON (10) ----------
  {
    id: 'c_ticking_wick_charm',
    name: 'Ticking Wick Charm',
    rarity: 'common',
    price: 12,
    hooks: { burnOnHit: { chance: 0.15, dps: 3, duration: 2 } },
    desc: 'Hits have a 15% chance to ignite enemies for 3 damage per second for 2 seconds.',
  },
  {
    id: 'c_magpie_bellows',
    name: 'Magpie Bellows',
    rarity: 'common',
    price: 10,
    hooks: { pickupRadius: { add: 40 } },
    desc: 'Increases your material pickup range by 40 units.',
  },
  {
    id: 'c_mendfinch',
    name: 'Mendfinch',
    rarity: 'common',
    price: 12,
    hooks: { materialHeal: { chance: 0.1, amount: 2 } },
    desc: 'Picking up a material has a 10% chance to heal you for 2 HP.',
  },
  {
    id: 'c_stitchwork_box',
    name: 'Stitchwork Box',
    rarity: 'common',
    price: 11,
    hooks: { roomClearHeal: { amount: 6 } },
    desc: 'Heal 6 HP at each room clear.',
  },
  {
    id: 'c_burr_locket',
    name: 'Burr Locket',
    rarity: 'common',
    price: 10,
    stats: { armor: 1 },
    hooks: { thorns: { damage: 4 } },
    desc: 'Enemies that touch you take 4 damage.',
  },
  {
    id: 'c_flint_knuckle_gear',
    name: 'Flint Knuckle Gear',
    rarity: 'common',
    price: 13,
    hooks: { dodgeToDamage: { bonus: 10, duration: 2 } },
    desc: 'After dodging an attack, gain +10% Damage for 2 seconds.',
  },
  {
    id: 'c_tallymans_abacus',
    name: "Tallyman's Abacus",
    rarity: 'common',
    price: 14,
    hooks: { xpBonus: { percent: 8 } },
    desc: 'Gain +8% XP from materials.',
    tags: ['economy'],
  },
  {
    id: 'c_gutter_magnet',
    name: 'Gutter Magnet',
    rarity: 'common',
    price: 13,
    hooks: { doubleMaterials: { chance: 0.05 } },
    desc: 'Your kills have a 5% chance to drop double materials.',
    tags: ['economy'],
  },
  {
    id: 'c_jarred_stormfly',
    name: 'Jarred Stormfly',
    rarity: 'common',
    price: 14,
    hooks: { chainOnHit: { chance: 0.1, damage: 4, range: 60 } },
    desc: 'Hits have a 10% chance to arc lightning for 4 damage to an enemy within 60 units.',
  },
  {
    id: 'c_coldsnap_vial',
    name: 'Coldsnap Vial',
    rarity: 'common',
    price: 12,
    hooks: { slowOnHit: { chance: 0.15, mult: 0.7, duration: 1 } },
    desc: 'Hits have a 15% chance to slow enemies to 70% speed for 1 second.',
  },
  // ---------- UNCOMMON (13) ----------
  {
    id: 'c_choirmasters_bell',
    name: "Choirmaster's Bell",
    rarity: 'uncommon',
    price: 26,
    hooks: { allyAura: { radius: 120, stats: { damage: 5 } } },
    desc: 'Allies within 120 units gain +5% Damage (does not affect you).',
    tags: ['aura'],
  },
  {
    id: 'c_emberkeeper_lantern',
    name: 'Emberkeeper Lantern',
    rarity: 'uncommon',
    price: 24,
    hooks: { allyAura: { radius: 120, stats: { hpRegen: 2 } } },
    desc: 'Allies within 120 units gain +2 HP Regeneration (does not affect you).',
    tags: ['aura'],
  },
  {
    id: 'c_coin_drip_ledger',
    name: 'Coin-Drip Ledger',
    rarity: 'uncommon',
    price: 25,
    hooks: { interest: { rate: 5, cap: 15 } },
    desc: 'At each room clear, gain 5% of your held materials as interest (max 15).',
    tags: ['economy'],
  },
  {
    id: 'c_peddlers_loose_cog',
    name: "Peddler's Loose Cog",
    rarity: 'uncommon',
    price: 22,
    hooks: { freeRerolls: { count: 1 } },
    desc: 'Gain 1 free reroll at each shop.',
    tags: ['economy'],
  },
  {
    id: 'c_hagglers_monocle',
    name: "Haggler's Monocle",
    rarity: 'uncommon',
    price: 26,
    hooks: { shopDiscount: { percent: 10 } },
    desc: 'Shop prices are reduced by 10% for you.',
    tags: ['economy'],
  },
  {
    id: 'c_leech_glass_prism',
    name: 'Leech-Glass Prism',
    rarity: 'uncommon',
    price: 24,
    stats: { critChance: 3 },
    hooks: { critHeal: { amount: 3 } },
    desc: 'Critical hits heal you for 3 HP.',
  },
  {
    id: 'c_latchwork_aegis',
    name: 'Latchwork Aegis',
    rarity: 'uncommon',
    price: 28,
    hooks: { blockShield: { cooldown: 12 } },
    desc: 'Automatically blocks one hit every 12 seconds.',
  },
  {
    id: 'c_popping_marrow_jar',
    name: 'Popping Marrow Jar',
    rarity: 'uncommon',
    price: 27,
    hooks: { killExplode: { chance: 0.12, damage: 15, radius: 70 } },
    desc: 'Kills have a 12% chance to explode for 15 damage in a 70 unit radius.',
  },
  {
    id: 'c_wardenbreaker_fang',
    name: 'Wardenbreaker Fang',
    rarity: 'uncommon',
    price: 28,
    hooks: { eliteBossDamage: { bonus: 15 } },
    desc: 'Deal +15% damage to elites and bosses.',
  },
  {
    id: 'c_ram_piston_gauntlet',
    name: 'Ram-Piston Gauntlet',
    rarity: 'uncommon',
    price: 22,
    hooks: { knockbackBoost: { mult: 0.5 } },
    desc: 'Your knockback is increased by 50%.',
  },
  {
    id: 'c_awlwork_needle',
    name: 'Awlwork Needle',
    rarity: 'uncommon',
    price: 26,
    hooks: { extraPierce: { add: 1 } },
    desc: 'Your projectiles pierce +1 enemy.',
  },
  {
    id: 'c_tinkers_oilheart',
    name: "Tinker's Oilheart",
    rarity: 'uncommon',
    price: 25,
    stats: { engineering: 2 },
    hooks: { summonBoost: { damage: 15, hp: 15 } },
    desc: 'Your summons and turrets gain +15% damage and +15% HP.',
  },
  {
    id: 'c_cornered_hedgeknot',
    name: 'Cornered Hedgeknot',
    rarity: 'uncommon',
    price: 23,
    hooks: { lowHpBonus: { threshold: 0.5, stats: { armor: 4 } } },
    desc: 'While below 50% HP, gain +4 Armor.',
  },
  // ---------- RARE (11) ----------
  {
    id: 'c_drumheart_reliquary',
    name: 'Drumheart Reliquary',
    rarity: 'rare',
    price: 55,
    hooks: { allyAura: { radius: 140, stats: { attackSpeed: 8, speed: 5 } } },
    desc: 'Allies within 140 units gain +8% Attack Speed and +5% Speed (does not affect you).',
    tags: ['aura'],
  },
  {
    id: 'c_galvanic_bloomcoil',
    name: 'Galvanic Bloomcoil',
    rarity: 'rare',
    price: 48,
    hooks: { reviveSpeed: { mult: 0.4 } },
    desc: 'You revive fallen allies 40% faster.',
  },
  {
    id: 'c_cindershade_effigy',
    name: 'Cindershade Effigy',
    rarity: 'rare',
    price: 60,
    stats: { maxHp: 8 },
    hooks: { secondWind: { healPercent: 0.3 } },
    desc: 'Once per floor, survive a lethal hit and heal to 30% of your Max HP.',
  },
  {
    id: 'c_frenzine_whirligig',
    name: 'Frenzine Whirligig',
    rarity: 'rare',
    price: 58,
    hooks: { killFrenzy: { attackSpeed: 4, duration: 3, maxStacks: 5 } },
    desc: 'Kills grant +4% Attack Speed for 3 seconds, stacking up to 5 times.',
  },
  {
    id: 'c_groaning_censer',
    name: 'Groaning Censer',
    rarity: 'rare',
    price: 52,
    hooks: { contactAura: { dps: 6, radius: 80 } },
    desc: 'Deal 6 damage per second to enemies within 80 units of you.',
  },
  {
    id: 'c_grudgekeg',
    name: 'Grudgekeg',
    rarity: 'rare',
    price: 50,
    hooks: { onHurtRetaliate: { damage: 20, radius: 90 } },
    desc: 'When you take a hit, unleash a nova dealing 20 damage in a 90 unit radius.',
  },
  {
    id: 'c_molting_idol',
    name: 'Molting Idol',
    rarity: 'rare',
    price: 56,
    hooks: { levelStats: { stats: { maxHp: 2, damage: 1 } } },
    desc: 'Gain +2 Max HP and +1% Damage at every level-up from now on.',
  },
  {
    id: 'c_stratum_chronograph',
    name: 'Stratum Chronograph',
    rarity: 'rare',
    price: 62,
    hooks: { floorStats: { stats: { armor: 2, damage: 3 } } },
    desc: 'Permanently gain +2 Armor and +3% Damage at the start of each floor.',
  },
  {
    id: 'c_marrowsip_phial',
    name: 'Marrowsip Phial',
    rarity: 'rare',
    price: 55,
    hooks: { maxHpOnKill: { amount: 1, cap: 20 } },
    desc: 'Gain +1 permanent Max HP per kill, up to +20 Max HP.',
  },
  {
    id: 'c_rootspur_terrarium',
    name: 'Rootspur Terrarium',
    rarity: 'rare',
    price: 54,
    stats: { harvesting: 4 },
    hooks: { harvestGrowth: { percent: 12 } },
    desc: 'Your Harvesting grows an extra +12% at each room clear.',
    tags: ['economy'],
  },
  {
    id: 'c_primed_coilstriker',
    name: 'Primed Coilstriker',
    rarity: 'rare',
    price: 46,
    stats: { critChance: 5 },
    hooks: { firstHitCrit: {} },
    desc: 'Your first hit in each room is always a critical hit.',
  },
  // ---------- LEGENDARY (6) ----------
  {
    id: 'c_manifold_barrelworks',
    name: 'Manifold Barrelworks',
    rarity: 'legendary',
    price: 120,
    hooks: { extraProjectiles: { add: 1 } },
    desc: 'Your ranged weapons fire +1 projectile.',
  },
  {
    id: 'c_vesuvian_heartfurnace',
    name: 'Vesuvian Heartfurnace',
    rarity: 'legendary',
    price: 115,
    hooks: {
      killExplode: { chance: 0.25, damage: 30, radius: 90 },
      burnOnHit: { chance: 0.2, dps: 5, duration: 3 },
    },
    desc: 'Kills have a 25% chance to explode for 30 damage in a 90 unit radius, and hits have a 20% chance to ignite for 5 damage per second for 3 seconds.',
  },
  {
    id: 'c_sovereign_gearheart',
    name: 'Sovereign Gearheart',
    rarity: 'legendary',
    price: 110,
    hooks: { allyAura: { radius: 160, stats: { damage: 8, armor: 3 } } },
    desc: 'Allies within 160 units gain +8% Damage and +3 Armor (does not affect you).',
    tags: ['aura'],
  },
  {
    id: 'c_gilded_gutworks',
    name: 'Gilded Gutworks',
    rarity: 'legendary',
    price: 100,
    hooks: {
      interest: { rate: 8, cap: 25 },
      freeRerolls: { count: 2 },
    },
    desc: 'At each room clear gain 8% of your held materials as interest (max 25), and gain 2 free rerolls at each shop.',
    tags: ['economy'],
  },
  {
    id: 'c_deathless_escapement',
    name: 'Deathless Escapement',
    rarity: 'legendary',
    price: 130,
    hooks: {
      blockShield: { cooldown: 8 },
      secondWind: { healPercent: 0.5 },
    },
    desc: 'Automatically blocks one hit every 8 seconds, and once per floor survive a lethal hit healing to 50% of your Max HP.',
  },
  {
    id: 'c_stormspine_conductor',
    name: 'Stormspine Conductor',
    rarity: 'legendary',
    price: 125,
    hooks: {
      chainOnHit: { chance: 0.25, damage: 12, range: 100 },
      extraPierce: { add: 2 },
    },
    desc: 'Hits have a 25% chance to arc lightning for 12 damage to an enemy within 100 units, and your projectiles pierce +2 enemies.',
  },
];
