// Undervault item pack A — 36 stat-package items (forged gear, minerals, tools, armor, provisions)
export const PART = [
  // ---- commons (22): small single/double stat bumps ----
  { id: 'a_iron_rivet_plate', name: 'Iron Rivet Plate', rarity: 'common', price: 12,
    stats: { armor: 1 } },
  { id: 'a_hardtack_ration', name: 'Hardtack Ration', rarity: 'common', price: 11,
    stats: { maxHp: 5 } },
  { id: 'a_whetted_pickhead', name: 'Whetted Pickhead', rarity: 'common', price: 12,
    stats: { meleeDamage: 5 } },
  { id: 'a_flintspark_shard', name: 'Flintspark Shard', rarity: 'common', price: 12,
    stats: { elementalDamage: 4 } },
  { id: 'a_oiled_bowstring', name: 'Oiled Bowstring', rarity: 'common', price: 12,
    stats: { rangedDamage: 5 } },
  { id: 'a_tin_lantern', name: 'Tin Lantern', rarity: 'common', price: 11,
    stats: { luck: 4 } },
  { id: 'a_cavemoss_salve', name: 'Cavemoss Salve', rarity: 'common', price: 10,
    stats: { hpRegen: 2 } },
  { id: 'a_lamprey_vial', name: 'Lamprey Vial', rarity: 'common', price: 13,
    stats: { lifeSteal: 2 } },
  { id: 'a_grindstone_chip', name: 'Grindstone Chip', rarity: 'common', price: 12,
    stats: { damage: 4 } },
  { id: 'a_springwound_cog', name: 'Springwound Cog', rarity: 'common', price: 13,
    stats: { attackSpeed: 5 } },
  { id: 'a_prospectors_loupe', name: "Prospector's Loupe", rarity: 'common', price: 12,
    stats: { critChance: 3 } },
  { id: 'a_tinkers_pliers', name: "Tinker's Pliers", rarity: 'common', price: 12,
    stats: { engineering: 2 } },
  { id: 'a_vaultwatch_spyglass', name: 'Vaultwatch Spyglass', rarity: 'common', price: 11,
    stats: { range: 15 } },
  { id: 'a_buckled_greaves', name: 'Buckled Greaves', rarity: 'common', price: 12,
    stats: { speed: 4 } },
  { id: 'a_softsole_boots', name: 'Softsole Boots', rarity: 'common', price: 12,
    stats: { dodge: 4 } },
  { id: 'a_orehauler_sack', name: 'Orehauler Sack', rarity: 'common', price: 11,
    stats: { harvesting: 3 } },
  { id: 'a_copper_band', name: 'Copper Band', rarity: 'common', price: 14,
    stats: { maxHp: 4, hpRegen: 1 } },
  { id: 'a_miners_mitts', name: "Miner's Mitts", rarity: 'common', price: 14,
    stats: { meleeDamage: 4, harvesting: 1 } },
  { id: 'a_fletchers_kit', name: "Fletcher's Kit", rarity: 'common', price: 14,
    stats: { rangedDamage: 4, range: 10 } },
  { id: 'a_embercoal_lump', name: 'Embercoal Lump', rarity: 'common', price: 15,
    stats: { elementalDamage: 3, damage: 3 } },
  { id: 'a_rustbitten_charm', name: 'Rustbitten Charm', rarity: 'common', price: 13,
    stats: { luck: 3, harvesting: 1 } },
  { id: 'a_padded_jerkin', name: 'Padded Jerkin', rarity: 'common', price: 14,
    stats: { armor: 1, maxHp: 3 } },

  // ---- uncommons (14): bigger bumps or 2-3 stat combos, a few tradeoffs ----
  { id: 'a_bloodgroove_blade', name: 'Bloodgroove Blade', rarity: 'uncommon', price: 26,
    stats: { lifeSteal: 3, meleeDamage: 6 } },
  { id: 'a_flywheel_gauntlet', name: 'Flywheel Gauntlet', rarity: 'uncommon', price: 25,
    stats: { attackSpeed: 9 } },
  { id: 'a_facet_cut_geode', name: 'Facet-Cut Geode', rarity: 'uncommon', price: 28,
    stats: { critChance: 6, luck: 5 } },
  { id: 'a_vault_servo_core', name: 'Vault Servo Core', rarity: 'uncommon', price: 27,
    stats: { engineering: 4 } },
  { id: 'a_quicksilver_soles', name: 'Quicksilver Soles', rarity: 'uncommon', price: 28,
    stats: { speed: 7, dodge: 5 } },
  { id: 'a_bulwark_pauldron', name: 'Bulwark Pauldron', rarity: 'uncommon', price: 27,
    stats: { armor: 3, maxHp: 8, speed: -3 } },
  { id: 'a_deepvein_ingot', name: 'Deepvein Ingot', rarity: 'uncommon', price: 26,
    stats: { damage: 10 } },
  { id: 'a_stormglass_arrowhead', name: 'Stormglass Arrowhead', rarity: 'uncommon', price: 30,
    stats: { rangedDamage: 8, elementalDamage: 6 } },
  { id: 'a_gluttons_stewpot', name: "Glutton's Stewpot", rarity: 'uncommon', price: 30,
    stats: { maxHp: 12, hpRegen: 3 } },
  { id: 'a_farsight_scope', name: 'Farsight Scope', rarity: 'uncommon', price: 27,
    stats: { range: 30, rangedDamage: 5 } },
  { id: 'a_prospectors_drill', name: "Prospector's Drill", rarity: 'uncommon', price: 29,
    stats: { harvesting: 5, engineering: 2 } },
  { id: 'a_redwrath_tonic', name: 'Redwrath Tonic', rarity: 'uncommon', price: 26,
    stats: { damage: 12, armor: -2 } },
  { id: 'a_ghost_iron_mail', name: 'Ghost-Iron Mail', rarity: 'uncommon', price: 28,
    stats: { dodge: 8, speed: 4, armor: -2 } },
  { id: 'a_cinderforge_hammer', name: 'Cinderforge Hammer', rarity: 'uncommon', price: 30,
    stats: { elementalDamage: 8, meleeDamage: 6, attackSpeed: -3 } },
];
