// Undervault item pack B — occult relics, tomes, elixirs, banners, idols (34 stat packages)
export const PART = [
  // ---------- UNCOMMON (12) ----------
  {
    id: 'b_ashen_grimoire',
    name: 'Ashen Grimoire',
    rarity: 'uncommon',
    price: 26,
    stats: { elementalDamage: 8, luck: 3 },
  },
  {
    id: 'b_vellum_psalter',
    name: 'Vellum Psalter',
    rarity: 'uncommon',
    price: 24,
    stats: { hpRegen: 3, maxHp: 8 },
  },
  {
    id: 'b_molten_idol',
    name: 'Molten Idol',
    rarity: 'uncommon',
    price: 28,
    stats: { meleeDamage: 9, armor: 2 },
  },
  {
    id: 'b_whisperwind_banner',
    name: 'Whisperwind Banner',
    rarity: 'uncommon',
    price: 27,
    stats: { speed: 6, dodge: 5 },
  },
  {
    id: 'b_ratcatchers_elixir',
    name: "Ratcatcher's Elixir",
    rarity: 'uncommon',
    price: 30,
    stats: { luck: 8, harvesting: 5 },
  },
  {
    id: 'b_cogbound_reliquary',
    name: 'Cogbound Reliquary',
    rarity: 'uncommon',
    price: 29,
    stats: { engineering: 4, range: 12 },
  },
  {
    id: 'b_bloodwax_candle',
    name: 'Bloodwax Candle',
    rarity: 'uncommon',
    price: 32,
    stats: { lifeSteal: 4, damage: 6 },
  },
  {
    id: 'b_gravedust_phial',
    name: 'Gravedust Phial',
    rarity: 'uncommon',
    price: 31,
    stats: { critChance: 6, meleeDamage: 6 },
  },
  {
    id: 'b_ossuary_charm',
    name: 'Ossuary Charm',
    rarity: 'uncommon',
    price: 25,
    stats: { armor: 3, maxHp: 7 },
  },
  {
    id: 'b_sable_hymnal',
    name: 'Sable Hymnal',
    rarity: 'uncommon',
    price: 33,
    stats: { rangedDamage: 8, attackSpeed: 4 },
  },
  {
    id: 'b_tallow_fetish',
    name: 'Tallow Fetish',
    rarity: 'uncommon',
    price: 22,
    stats: { harvesting: 6, maxHp: 5 },
  },
  {
    id: 'b_lodestone_rosary',
    name: 'Lodestone Rosary',
    rarity: 'uncommon',
    price: 30,
    stats: { range: 15, rangedDamage: 6 },
  },
  // ---------- RARE (14) — every one carries a tradeoff ----------
  {
    id: 'b_grimoire_of_cinders',
    name: 'Grimoire of Cinders',
    rarity: 'rare',
    price: 55,
    stats: { elementalDamage: 16, attackSpeed: -6 },
  },
  {
    id: 'b_banner_of_the_red_vow',
    name: 'Banner of the Red Vow',
    rarity: 'rare',
    price: 58,
    stats: { meleeDamage: 18, range: -15 },
  },
  {
    id: 'b_widows_vintage',
    name: "Widow's Vintage",
    rarity: 'rare',
    price: 62,
    stats: { lifeSteal: 7, damage: 12, hpRegen: -3 },
  },
  {
    id: 'b_idol_of_hollow_kings',
    name: 'Idol of Hollow Kings',
    rarity: 'rare',
    price: 54,
    stats: { maxHp: 18, armor: 4, speed: -7 },
  },
  {
    id: 'b_occult_ledger',
    name: 'Occult Ledger',
    rarity: 'rare',
    price: 60,
    stats: { luck: 14, harvesting: 8, damage: -6 },
  },
  {
    id: 'b_tinkers_black_codex',
    name: "Tinker's Black Codex",
    rarity: 'rare',
    price: 63,
    stats: { engineering: 7, range: 20, meleeDamage: -10 },
  },
  {
    id: 'b_phial_of_quicksilver',
    name: 'Phial of Quicksilver',
    rarity: 'rare',
    price: 64,
    stats: { attackSpeed: 14, speed: 8, armor: -4 },
  },
  {
    id: 'b_corpselight_lantern',
    name: 'Corpselight Lantern',
    rarity: 'rare',
    price: 61,
    stats: { critChance: 12, meleeDamage: 10, maxHp: -8 },
  },
  {
    id: 'b_banner_of_last_breath',
    name: 'Banner of Last Breath',
    rarity: 'rare',
    price: 59,
    stats: { dodge: 12, speed: 10, maxHp: -10 },
  },
  {
    id: 'b_chained_saints_femur',
    name: "Chained Saint's Femur",
    rarity: 'rare',
    price: 52,
    stats: { armor: 7, hpRegen: 4, dodge: -8 },
  },
  {
    id: 'b_elixir_of_pale_fire',
    name: 'Elixir of Pale Fire',
    rarity: 'rare',
    price: 57,
    stats: { elementalDamage: 12, critChance: 8, lifeSteal: -4 },
  },
  {
    id: 'b_tome_of_severed_names',
    name: 'Tome of Severed Names',
    rarity: 'rare',
    price: 56,
    stats: { damage: 16, luck: -8 },
  },
  {
    id: 'b_gilded_vault_idol',
    name: 'Gilded Vault Idol',
    rarity: 'rare',
    price: 53,
    stats: { harvesting: 14, luck: 6, attackSpeed: -6 },
  },
  {
    id: 'b_sightless_oracles_eye',
    name: "Sightless Oracle's Eye",
    rarity: 'rare',
    price: 66,
    stats: { range: 30, rangedDamage: 12, dodge: -6 },
  },
  // ---------- LEGENDARY (8) — heavy power, heavy price ----------
  {
    id: 'b_the_bleeding_codex',
    name: 'The Bleeding Codex',
    rarity: 'legendary',
    price: 120,
    stats: { damage: 25, lifeSteal: 8, maxHp: -15 },
  },
  {
    id: 'b_ninth_vault_warbanner',
    name: 'Ninth Vault Warbanner',
    rarity: 'legendary',
    price: 125,
    stats: { meleeDamage: 28, critChance: 10, range: -25 },
  },
  {
    id: 'b_elixir_of_the_comet',
    name: 'Elixir of the Comet',
    rarity: 'legendary',
    price: 118,
    stats: { attackSpeed: 22, speed: 12, armor: -8 },
  },
  {
    id: 'b_idol_of_the_ore_mother',
    name: 'Idol of the Ore Mother',
    rarity: 'legendary',
    price: 110,
    stats: { harvesting: 22, luck: 15, damage: -12 },
  },
  {
    id: 'b_black_sutra_of_gears',
    name: 'Black Sutra of Gears',
    rarity: 'legendary',
    price: 122,
    stats: { engineering: 12, range: 40, meleeDamage: -18 },
  },
  {
    id: 'b_shroudwalker_banner',
    name: 'Shroudwalker Banner',
    rarity: 'legendary',
    price: 115,
    stats: { dodge: 20, speed: 15, maxHp: -12 },
  },
  {
    id: 'b_grimoire_of_stormglass',
    name: 'Grimoire of Stormglass',
    rarity: 'legendary',
    price: 130,
    stats: { elementalDamage: 26, rangedDamage: 15, hpRegen: -5 },
  },
  {
    id: 'b_anvilheart_idol',
    name: 'Anvilheart Idol',
    rarity: 'legendary',
    price: 112,
    stats: { maxHp: 25, armor: 10, speed: -12 },
  },
];
